version: "2"
services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - ./db/pgsql_init:/docker-entrypoint-initdb.d
      - ./db/pgsql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGPASSWORD
      - POSTGRES_DB
      - DATABASE_HOST
    ports:
      - "5432:5432"
volumes:
  pgsql_data: